question_box/config/routes.rb
Rails.application.routes.draw do
	resources :answers, only: [:new, :create, :show, :update, :destroy]

  resources :questions
  root to: "questions#index"

  get 'posts/index'

  get 'posts/show'

  get '/login' => 'users#new'

  get 'tags/new'

  get 'tags/index'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/show'

  get 'users/update'

  get 'users/destroy'


root to: 'questions#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

question_box/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :tag
  belongs_to :user
end

question_box/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

question_box/app/models/post.rb
class Post < ApplicationRecord
end

question_box/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :tag

  has_many :answers

end

question_box/app/models/tag.rb
class Tag < ApplicationRecord
 has_many :questions
end

question_box/app/models/user.rb
class User < ApplicationRecord
  has_many :answers
  has_many :questions
end

question_box/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
		@answer = Answer.new
  end

  def create
		@answer = Answer.new(answer_params)
		@answer[:rating] = 0
		@answer[:correct] = false
		if @answer.save
			redirect_to @answer, notice: 'Answer was successfully created.'
		else
			render 'new'
		end
  end

  def show
  end

  def update
		if @answer.update(answer_params)
			redirect_to @answer
		else
			render 'edit'
		end
  end

  def destroy
		@answer.destroy
	  redirect_to answers_show_path, notice: 'Answer was successfully deleted.'
  end
	
	private
	
	def set_answer
		@answer = Answer.find(params[:id])
	end
	
	def answer_params
      params.require(:answer).permit(:content)
  end
end

question_box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    private 
  
      def logged_in?
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end

      helper_method :logged_in?
end

question_box/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

question_box/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.page(params[:page]).per(5)
  end
  
  def new
   @question = Question.new
  end

  def create
   @question = Question.new(question_params)

   if @question.save
    redirect_to @question
   else
    render "new"
   end
  end

  def show

    @questions = Question.page(params[:page]).per(15)

  end

  def update
  end

  def destroy
  end

  private

  def question_params
   params.require(:question).permit(:title, :content, :user_id, :tag_id, :rating)
  end
end

question_box/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
      @user = User.find_by_email(params[:email])
      if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
        redirect_to '/books'
      else
        redirect_to '/login'
      end
   end
  
   def destroy
	  session[:user_id] = nil
	  redirect_to root_path
   end

end

question_box/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def update
  end

  def destroy
  end
end

question_box/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else 
      render :new
    end
  end

  def show
    
  end

  def update
  end

  def destroy
  end

  private 

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:displayname, :email, :password, :password_confirmation)
    end


end

question_box/app/helpers/answers_helper.rb
module AnswersHelper
end

question_box/app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)

    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

question_box/app/helpers/posts_helper.rb
module PostsHelper
end

question_box/app/helpers/questions_helper.rb
module QuestionsHelper
end

question_box/app/helpers/sessions_helper.rb
module SessionsHelper
end

question_box/app/helpers/tags_helper.rb
module TagsHelper
end

question_box/app/helpers/users_helper.rb
module UsersHelper
end

question_box/app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
			<h2><%= pluralize(answer.errors.count, "error") %>
			prohibited this book from being saved:</h2>
			
			<ul>
			<% answer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
    </div>
  <% end %>

  <div class="field">
		<%= form.label :content %>
    <%= form.text_field :content, id: :answer_content %>
  </div>

  <div class="actions">
		<%= form.submit %>
  </div>

<% end %>

question_box/app/views/answers/create.html.erb
<h1>Create Answer</h1>

<%= render 'form', answer: @answer %>

<% link_to 'Back', answers_show_path %>

question_box/app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

question_box/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<% link_to 'Back', answers_path %>

question_box/app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

question_box/app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>

question_box/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

question_box/app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

question_box/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

question_box/app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

question_box/app/views/questions/index.html.erb
<h1>this is the index</h1>

question_box/app/views/questions/new.html.erb
<h1>creating a new question</h1>
 <%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :user_id %>
  <%= f.number_field :user_id %>

  <%= f.label :tag_id %>
  <%= f.number_field :tag_id %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.submit "submit" %>
 <% end %>

question_box/app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p><%= @question.title %></p>
<p><%= @question.content %></p>

<div class="container">
  <div class="row">
    <%= render @questions %>
  </div>

  <%= paginate @questions %>
</div>

question_box/app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

question_box/app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

question_box/app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

question_box/app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

question_box/app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

question_box/app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>

question_box/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :post_password %>
  </div>

    <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :post_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

question_box/app/views/users/new.html.erb
<h1>Sign up for Question Box</h1>

<%= render 'form', user: @user %>

question_box/app/views/users/show.html.erb
<h1>Profile</h1>

<div class="col-sm-4">
  <span><%= @user.displayname %>
  <% if logged_in? && session[:user_id] == @user.id %>
    <%= link_to 'Edit', edit_user_path %>
  <% end %>
  </span>
</div>

<div class="col-sm-8">

</div>